[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/202877297",
    "html_url": "https://github.com/pandas-dev/pandas/issues/12729#issuecomment-202877297",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/12729",
    "id": 202877297,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIwMjg3NzI5Nw==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-03-29T12:48:24Z",
    "updated_at": "2016-03-29T12:48:24Z",
    "author_association": "CONTRIBUTOR",
    "body": "This is at odds with the wheels built directly by the numpy on master. see [here](https://travis-ci.org/pydata/pandas/jobs/118605953). 2 known failures on pandas side ATM due to some compat issues. This is master numpy / master pandas.\n\nThe error you are seeing is rather old IIRC.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/202891397",
    "html_url": "https://github.com/pandas-dev/pandas/issues/12729#issuecomment-202891397",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/12729",
    "id": 202891397,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIwMjg5MTM5Nw==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-03-29T13:24:00Z",
    "updated_at": "2016-03-29T13:24:13Z",
    "author_association": "CONTRIBUTOR",
    "body": "We have this changing from an `IndexError` in numpy < 1.11 to a `TypeError` in 1.11. Was this changed reverted before 1.11?\n@charris @shoyer \n\n```\nIn [32]: arr = np.arange(0,2).astype('M8[ns]')\n\nIn [33]: arr\nOut[33]: \narray(['1969-12-31T19:00:00.000000000-0500',\n       '1969-12-31T19:00:00.000000001-0500'], dtype='datetime64[ns]')\n\nIn [34]: arr[slice('2014',None,None)]\nIndexError: invalid slice\n\nIn [35]: np.__version__\nOut[35]: '1.10.4'\n```\n\n```\n>>> np.__version__\n'1.11.0b3'\n>>> arr = np.arange(0,2).astype('M8[ns]')\n>>> arr\narray(['1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000001'], dtype='datetime64[ns]')\n>>> arr[slice('2014',None,None)]\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\nIndexError: failed to coerce slice entry of type str to integer\n```\n\n```\n>>> np.__version__\n'1.12.0.dev0+75c5af3'\n>>> arr = np.arange(0,2).astype('M8[ns]')\n>>> arr[slice('2014',None,None)]\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\nTypeError: slice indices must be integers or None or have an __index__ method\n```\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/202980868",
    "html_url": "https://github.com/pandas-dev/pandas/issues/12729#issuecomment-202980868",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/12729",
    "id": 202980868,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIwMjk4MDg2OA==",
    "user": {
      "login": "charris",
      "id": 77272,
      "node_id": "MDQ6VXNlcjc3Mjcy",
      "avatar_url": "https://avatars3.githubusercontent.com/u/77272?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/charris",
      "html_url": "https://github.com/charris",
      "followers_url": "https://api.github.com/users/charris/followers",
      "following_url": "https://api.github.com/users/charris/following{/other_user}",
      "gists_url": "https://api.github.com/users/charris/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/charris/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/charris/subscriptions",
      "organizations_url": "https://api.github.com/users/charris/orgs",
      "repos_url": "https://api.github.com/users/charris/repos",
      "events_url": "https://api.github.com/users/charris/events{/privacy}",
      "received_events_url": "https://api.github.com/users/charris/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-03-29T16:15:18Z",
    "updated_at": "2016-03-29T16:15:18Z",
    "author_association": "NONE",
    "body": "I don't see where you tested with 1.11.0, the reversion was in 1.11.0rc1\n\n```\ncommit 466d60d364dfc979ccffa58b5c8212137e6b2a27\nAuthor: Charles Harris <charlesr.harris@gmail.com>\nDate:   Sun Feb 14 11:49:29 2016 -0700\n\n    Revert #6271 from charris/change-deprecated-indexes-to-error\n\n    This reverts commit 0b0206c1617841ed2e5324de752ee8ede2cce791,\n    reversing changes made to 438cdd3d75a0bb606e7ab7f96e59744c9b78d748.\n\n    This reverts all the changes of indexing deprecation warnings to\n    errors that were done prior to branching Numpy 1.11.x. It is easier\n    to make a clean reversion here than to pick out those bits involving\n    integer indexing specifically. As the aim of this reversion is to\n    give downstream projects a bit more time to adapt I don't think the\n    slight overkill is worth worrying about, especially if downstream\n    projects start paying close attention to deprecations.\n\n    The 1.11.0-notes also need updating, but I will submit a separate\n    PR against master for that.\n\n    Closes #7162.\n```\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/202983209",
    "html_url": "https://github.com/pandas-dev/pandas/issues/12729#issuecomment-202983209",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/12729",
    "id": 202983209,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIwMjk4MzIwOQ==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-03-29T16:20:49Z",
    "updated_at": "2016-03-29T16:20:49Z",
    "author_association": "CONTRIBUTOR",
    "body": "it's the same (forgot to pull tags)\n\nok so you reverted this change - will update on our side\n"
  }
]
