[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/242230727",
    "html_url": "https://github.com/pandas-dev/pandas/issues/14080#issuecomment-242230727",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/14080",
    "id": 242230727,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0MjIzMDcyNw==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-24T22:40:10Z",
    "updated_at": "2016-08-24T22:40:10Z",
    "author_association": "CONTRIBUTOR",
    "body": "thought we had an issue for this....\n\nits an wraparound thing I think.\n\nPR's are welcome.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/242373427",
    "html_url": "https://github.com/pandas-dev/pandas/issues/14080#issuecomment-242373427",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/14080",
    "id": 242373427,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0MjM3MzQyNw==",
    "user": {
      "login": "bhaprayan",
      "id": 8630642,
      "node_id": "MDQ6VXNlcjg2MzA2NDI=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/8630642?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bhaprayan",
      "html_url": "https://github.com/bhaprayan",
      "followers_url": "https://api.github.com/users/bhaprayan/followers",
      "following_url": "https://api.github.com/users/bhaprayan/following{/other_user}",
      "gists_url": "https://api.github.com/users/bhaprayan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bhaprayan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bhaprayan/subscriptions",
      "organizations_url": "https://api.github.com/users/bhaprayan/orgs",
      "repos_url": "https://api.github.com/users/bhaprayan/repos",
      "events_url": "https://api.github.com/users/bhaprayan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bhaprayan/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-25T12:47:11Z",
    "updated_at": "2016-08-25T12:47:11Z",
    "author_association": "NONE",
    "body": "Any pointers on how to fix this?\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/242461833",
    "html_url": "https://github.com/pandas-dev/pandas/issues/14080#issuecomment-242461833",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/14080",
    "id": 242461833,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0MjQ2MTgzMw==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-25T16:54:32Z",
    "updated_at": "2016-08-25T16:54:32Z",
    "author_association": "CONTRIBUTOR",
    "body": "step thru the code - this hits cython at some point (for the add) then again for the construction of a new Timestamp -  think it's crashing there\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/242742080",
    "html_url": "https://github.com/pandas-dev/pandas/issues/14080#issuecomment-242742080",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/14080",
    "id": 242742080,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjc0MjA4MA==",
    "user": {
      "login": "bhaprayan",
      "id": 8630642,
      "node_id": "MDQ6VXNlcjg2MzA2NDI=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/8630642?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bhaprayan",
      "html_url": "https://github.com/bhaprayan",
      "followers_url": "https://api.github.com/users/bhaprayan/followers",
      "following_url": "https://api.github.com/users/bhaprayan/following{/other_user}",
      "gists_url": "https://api.github.com/users/bhaprayan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bhaprayan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bhaprayan/subscriptions",
      "organizations_url": "https://api.github.com/users/bhaprayan/orgs",
      "repos_url": "https://api.github.com/users/bhaprayan/repos",
      "events_url": "https://api.github.com/users/bhaprayan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bhaprayan/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-26T13:55:42Z",
    "updated_at": "2016-08-26T13:57:54Z",
    "author_association": "NONE",
    "body": "I generated the stack trace, and stepped through the code. I've isolated the problem to the subset of the trace I've attached.\nIt crashes at the point where it's trying to multiply \"self.n\" and \"self._inc\", within the Delta function of the Tick class. Any suggestions on fixing this?\n\n`> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(393)**radd**()\n-> def **radd**(self, other):\n(Pdb) s\n\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(394)**radd**()\n> -> return self.**add**(other)\n> (Pdb) s\n> --Call--\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2698)**add**()\n> -> def **add**(self, other):\n> (Pdb) s\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2699)**add**()\n> -> if isinstance(other, Tick):\n> (Pdb) s\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2704)**add**()\n> -> elif isinstance(other, ABCPeriod):\n> (Pdb) s\n> --Call--\n> /home/bhaprayan/Workspace/pandas/pandas/types/generic.py(7)_check()\n> -> @classmethod\n> (Pdb) s\n> /home/bhaprayan/Workspace/pandas/pandas/types/generic.py(9)_check()\n> -> return getattr(inst, attr, '_typ') in comp\n> (Pdb) s\n> --Return--\n> /home/bhaprayan/Workspace/pandas/pandas/types/generic.py(9)_check()->False\n> -> return getattr(inst, attr, '_typ') in comp\n> (Pdb) s\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2706)__add__()\n> -> try:\n> (Pdb) s\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2707)**add**()\n> -> return self.apply(other)\n> (Pdb) s\n> --Call--\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2746)apply()\n> -> def apply(self, other):\n> (Pdb) s\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2748)apply()\n> -> if isinstance(other, (datetime, np.datetime64, date)):\n> (Pdb) s\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2749)apply()\n> -> return as_timestamp(other) + self\n> (Pdb) s\n> --Call--\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(35)as_timestamp()\n> -> def as_timestamp(obj):\n> (Pdb) s\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(36)as_timestamp()\n> -> if isinstance(obj, Timestamp):\n> (Pdb) s\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(37)as_timestamp()\n> -> return obj\n> (Pdb) s\n> --Return--\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(37)as_timestamp()->Timestam...0:00:00')\n> -> return obj\n> (Pdb) s\n> --Call--\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2738)delta()\n> -> @property\n> (Pdb) s\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2740)delta()\n> -> return self.n \\* self._inc\n> (Pdb) s\n> **OverflowError: 'Python int too large to convert to C long'**\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2740)delta()\n> -> return self.n \\* self._inc\n> (Pdb) s\n> --Return--\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2740)delta()->None\n> -> return self.n \\* self._inc\n> (Pdb) s\n> --Call--\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(393)__radd__()\n> -> def **radd**(self, other):\n> (Pdb) \n> `\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/242841973",
    "html_url": "https://github.com/pandas-dev/pandas/issues/14080#issuecomment-242841973",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/14080",
    "id": 242841973,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjg0MTk3Mw==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-26T20:23:53Z",
    "updated_at": "2016-08-26T20:23:53Z",
    "author_association": "CONTRIBUTOR",
    "body": "so I think that multiplcation needs a guard on overflow\n\n```\nIn [2]: np.iinfo(np.int64).max\nOut[2]: 9223372036854775807\n\nIn [3]: np.int64(1000000)*np.int64(86400*1e9)\n/Users/jreback/miniconda/bin/ipython:1: RuntimeWarning: overflow encountered in long_scalars\n  #!/bin/bash /Users/jreback/miniconda/bin/python.app\nOut[3]: -5833720368547758080\n```\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/242893809",
    "html_url": "https://github.com/pandas-dev/pandas/issues/14080#issuecomment-242893809",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/14080",
    "id": 242893809,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjg5MzgwOQ==",
    "user": {
      "login": "bhaprayan",
      "id": 8630642,
      "node_id": "MDQ6VXNlcjg2MzA2NDI=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/8630642?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bhaprayan",
      "html_url": "https://github.com/bhaprayan",
      "followers_url": "https://api.github.com/users/bhaprayan/followers",
      "following_url": "https://api.github.com/users/bhaprayan/following{/other_user}",
      "gists_url": "https://api.github.com/users/bhaprayan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bhaprayan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bhaprayan/subscriptions",
      "organizations_url": "https://api.github.com/users/bhaprayan/orgs",
      "repos_url": "https://api.github.com/users/bhaprayan/repos",
      "events_url": "https://api.github.com/users/bhaprayan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bhaprayan/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-08-27T03:51:53Z",
    "updated_at": "2016-08-27T03:52:50Z",
    "author_association": "NONE",
    "body": "First, I set a guard on the multiplication overflow. However it's still stuck in a recursive loop, where after catching the OverflowError, it still calls **radd**.\n\n`ipdb> s\n\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2741)delta()\n>    2739     def delta(self):\n>    2740         try:\n> -> 2741             self.n \\* self._inc\n>    2742         except OverflowError:\n>    2743             raise\n\nipdb> s\nOverflowError: 'Python int too large to convert to C long'\n\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2741)delta()\n>    2739     def delta(self):\n>    2740         try:\n> -> 2741             self.n \\* self._inc\n>    2742         except OverflowError:\n>    2743             raise\n\nipdb> s\n\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2742)delta()\n>    2740         try:\n>    2741             self.n \\* self._inc\n> -> 2742         except OverflowError:\n>    2743             raise\n>    2744 \n\nipdb> s\n\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2743)delta()\n>    2741             self.n \\* self._inc\n>    2742         except OverflowError:\n> -> 2743             raise\n>    2744 \n>    2745     @property\n\nipdb> s\n--Return--\nNone\n\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(2743)delta()\n>    2741             self.n \\* self._inc\n>    2742         except OverflowError:\n> -> 2743             raise\n>    2744 \n>    2745     @property\n\nipdb> s\n--Call--\n\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(393)**radd**()\n>     391             return NotImplemented\n>     392 \n> --> 393     def **radd**(self, other):\n>     394         return self.**add**(other)\n>     395 \n\nipdb> s\n\n> /home/bhaprayan/Workspace/pandas/pandas/tseries/offsets.py(394)**radd**()\n>     392 \n>     393     def **radd**(self, other):\n> --> 394         return self.**add**(other)\n>     395 \n>     396     def **sub**(self, other):\n> `\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/304395618",
    "html_url": "https://github.com/pandas-dev/pandas/issues/14080#issuecomment-304395618",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/14080",
    "id": 304395618,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMwNDM5NTYxOA==",
    "user": {
      "login": "guygoldberg",
      "id": 23085120,
      "node_id": "MDQ6VXNlcjIzMDg1MTIw",
      "avatar_url": "https://avatars1.githubusercontent.com/u/23085120?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/guygoldberg",
      "html_url": "https://github.com/guygoldberg",
      "followers_url": "https://api.github.com/users/guygoldberg/followers",
      "following_url": "https://api.github.com/users/guygoldberg/following{/other_user}",
      "gists_url": "https://api.github.com/users/guygoldberg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/guygoldberg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/guygoldberg/subscriptions",
      "organizations_url": "https://api.github.com/users/guygoldberg/orgs",
      "repos_url": "https://api.github.com/users/guygoldberg/repos",
      "events_url": "https://api.github.com/users/guygoldberg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/guygoldberg/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-05-26T21:51:35Z",
    "updated_at": "2017-05-26T21:51:35Z",
    "author_association": "CONTRIBUTOR",
    "body": "Looks like this issue was already solved, by running the reproduction scenario now I get a clear exception:\r\n`OverflowError: the add operation between <100000000000000000000000000000000000000000000000000 * Days> and 2000-01-01 00:00:00 will overflow`"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/304408071",
    "html_url": "https://github.com/pandas-dev/pandas/issues/14080#issuecomment-304408071",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/14080",
    "id": 304408071,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMwNDQwODA3MQ==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-05-26T23:27:35Z",
    "updated_at": "2017-05-26T23:27:35Z",
    "author_association": "CONTRIBUTOR",
    "body": "great\r\n\r\ndo u want to do a PR with some tests ?"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/312514478",
    "html_url": "https://github.com/pandas-dev/pandas/issues/14080#issuecomment-312514478",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/14080",
    "id": 312514478,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMxMjUxNDQ3OA==",
    "user": {
      "login": "dsm054",
      "id": 980054,
      "node_id": "MDQ6VXNlcjk4MDA1NA==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/980054?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dsm054",
      "html_url": "https://github.com/dsm054",
      "followers_url": "https://api.github.com/users/dsm054/followers",
      "following_url": "https://api.github.com/users/dsm054/following{/other_user}",
      "gists_url": "https://api.github.com/users/dsm054/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dsm054/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dsm054/subscriptions",
      "organizations_url": "https://api.github.com/users/dsm054/orgs",
      "repos_url": "https://api.github.com/users/dsm054/repos",
      "events_url": "https://api.github.com/users/dsm054/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dsm054/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-07-02T20:16:43Z",
    "updated_at": "2017-07-02T20:16:43Z",
    "author_association": "CONTRIBUTOR",
    "body": "I put together a quick smoke test, and indeed it looks like things are generating exceptions like they should.\r\n\r\nBut two offsets, the FY5253Quarter and DateOffset cases, both take forever to fail, ~20s in one case, ~10s in the other, so something's different about them (I haven't given even a cursory glance)."
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/366765582",
    "html_url": "https://github.com/pandas-dev/pandas/issues/14080#issuecomment-366765582",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/14080",
    "id": 366765582,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM2Njc2NTU4Mg==",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-02-19T17:58:03Z",
    "updated_at": "2018-02-19T17:58:03Z",
    "author_association": "CONTRIBUTOR",
    "body": "this is already fixed in master if someone would like to add tests in a PR"
  }
]
