[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/19505450",
    "html_url": "https://github.com/pandas-dev/pandas/issues/3919#issuecomment-19505450",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/3919",
    "id": 19505450,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE5NTA1NDUw",
    "user": {
      "login": "cpcloud",
      "id": 417981,
      "node_id": "MDQ6VXNlcjQxNzk4MQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/417981?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cpcloud",
      "html_url": "https://github.com/cpcloud",
      "followers_url": "https://api.github.com/users/cpcloud/followers",
      "following_url": "https://api.github.com/users/cpcloud/following{/other_user}",
      "gists_url": "https://api.github.com/users/cpcloud/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cpcloud/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cpcloud/subscriptions",
      "organizations_url": "https://api.github.com/users/cpcloud/orgs",
      "repos_url": "https://api.github.com/users/cpcloud/repos",
      "events_url": "https://api.github.com/users/cpcloud/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cpcloud/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-06-15T23:47:20Z",
    "updated_at": "2013-06-15T23:47:20Z",
    "author_association": "MEMBER",
    "body": "arg this is an ipython issue.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/19795392",
    "html_url": "https://github.com/pandas-dev/pandas/issues/3919#issuecomment-19795392",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/3919",
    "id": 19795392,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE5Nzk1Mzky",
    "user": {
      "login": "jtratner",
      "id": 1598379,
      "node_id": "MDQ6VXNlcjE1OTgzNzk=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1598379?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jtratner",
      "html_url": "https://github.com/jtratner",
      "followers_url": "https://api.github.com/users/jtratner/followers",
      "following_url": "https://api.github.com/users/jtratner/following{/other_user}",
      "gists_url": "https://api.github.com/users/jtratner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jtratner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jtratner/subscriptions",
      "organizations_url": "https://api.github.com/users/jtratner/orgs",
      "repos_url": "https://api.github.com/users/jtratner/repos",
      "events_url": "https://api.github.com/users/jtratner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jtratner/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-06-21T02:32:27Z",
    "updated_at": "2013-06-21T02:32:27Z",
    "author_association": "CONTRIBUTOR",
    "body": "There is a ton in pytables... Is there (or could we write) a 'safe_format' function that just brute force skips unicode decode errors with a signature of `safe_format(fmt_string, *args, **kwargs)`\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/19795421",
    "html_url": "https://github.com/pandas-dev/pandas/issues/3919#issuecomment-19795421",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/3919",
    "id": 19795421,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE5Nzk1NDIx",
    "user": {
      "login": "jtratner",
      "id": 1598379,
      "node_id": "MDQ6VXNlcjE1OTgzNzk=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1598379?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jtratner",
      "html_url": "https://github.com/jtratner",
      "followers_url": "https://api.github.com/users/jtratner/followers",
      "following_url": "https://api.github.com/users/jtratner/following{/other_user}",
      "gists_url": "https://api.github.com/users/jtratner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jtratner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jtratner/subscriptions",
      "organizations_url": "https://api.github.com/users/jtratner/orgs",
      "repos_url": "https://api.github.com/users/jtratner/repos",
      "events_url": "https://api.github.com/users/jtratner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jtratner/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-06-21T02:33:51Z",
    "updated_at": "2013-06-21T02:33:51Z",
    "author_association": "CONTRIBUTOR",
    "body": "(many of them work on unsanitized user inputs, so the risk of getting something that can't be passed to string is non-trivial) \n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/19848355",
    "html_url": "https://github.com/pandas-dev/pandas/issues/3919#issuecomment-19848355",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/3919",
    "id": 19848355,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE5ODQ4MzU1",
    "user": {
      "login": "cpcloud",
      "id": 417981,
      "node_id": "MDQ6VXNlcjQxNzk4MQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/417981?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cpcloud",
      "html_url": "https://github.com/cpcloud",
      "followers_url": "https://api.github.com/users/cpcloud/followers",
      "following_url": "https://api.github.com/users/cpcloud/following{/other_user}",
      "gists_url": "https://api.github.com/users/cpcloud/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cpcloud/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cpcloud/subscriptions",
      "organizations_url": "https://api.github.com/users/cpcloud/orgs",
      "repos_url": "https://api.github.com/users/cpcloud/repos",
      "events_url": "https://api.github.com/users/cpcloud/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cpcloud/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-06-22T01:17:57Z",
    "updated_at": "2013-06-22T01:17:57Z",
    "author_association": "MEMBER",
    "body": "but u _could_ call `pprint_thing` on them\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/19849841",
    "html_url": "https://github.com/pandas-dev/pandas/issues/3919#issuecomment-19849841",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/3919",
    "id": 19849841,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE5ODQ5ODQx",
    "user": {
      "login": "jtratner",
      "id": 1598379,
      "node_id": "MDQ6VXNlcjE1OTgzNzk=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1598379?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jtratner",
      "html_url": "https://github.com/jtratner",
      "followers_url": "https://api.github.com/users/jtratner/followers",
      "following_url": "https://api.github.com/users/jtratner/following{/other_user}",
      "gists_url": "https://api.github.com/users/jtratner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jtratner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jtratner/subscriptions",
      "organizations_url": "https://api.github.com/users/jtratner/orgs",
      "repos_url": "https://api.github.com/users/jtratner/repos",
      "events_url": "https://api.github.com/users/jtratner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jtratner/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-06-22T03:22:36Z",
    "updated_at": "2013-06-22T03:22:36Z",
    "author_association": "CONTRIBUTOR",
    "body": "Well, for example, if you want to show the error to the user and use\nsomething like %s doesn't that end up doing implicit conversion to string?\nIt's littered all over and is convention in docs...\nOn Jun 21, 2013 9:18 PM, \"Phillip Cloud\" notifications@github.com wrote:\n\n> but u _could_ call pprint_thing on them\n> \n> â€”\n> Reply to this email directly or view it on GitHubhttps://github.com/pydata/pandas/issues/3919#issuecomment-19848355\n> .\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/19849866",
    "html_url": "https://github.com/pandas-dev/pandas/issues/3919#issuecomment-19849866",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/3919",
    "id": 19849866,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE5ODQ5ODY2",
    "user": {
      "login": "cpcloud",
      "id": 417981,
      "node_id": "MDQ6VXNlcjQxNzk4MQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/417981?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cpcloud",
      "html_url": "https://github.com/cpcloud",
      "followers_url": "https://api.github.com/users/cpcloud/followers",
      "following_url": "https://api.github.com/users/cpcloud/following{/other_user}",
      "gists_url": "https://api.github.com/users/cpcloud/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cpcloud/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cpcloud/subscriptions",
      "organizations_url": "https://api.github.com/users/cpcloud/orgs",
      "repos_url": "https://api.github.com/users/cpcloud/repos",
      "events_url": "https://api.github.com/users/cpcloud/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cpcloud/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-06-22T03:25:08Z",
    "updated_at": "2013-06-22T03:25:25Z",
    "author_association": "MEMBER",
    "body": "not necessarily:\n\n```\nIn [4]: mkdf(1, 1, c_idx_type='u').columns[0]\nOut[4]: u'1\\u05dd\\u05de3\\u05e4\\u05d2\\u05d47\\u05e3\\u05da'\n\nIn [5]: x = mkdf(1, 1, c_idx_type='u').columns[0]\n\nIn [6]: str(x)\n---------------------------------------------------------------------------\nUnicodeEncodeError                        Traceback (most recent call last)\n<ipython-input-6-68e10e3ad351> in <module>()\n----> 1 str(x)\n\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\u05d3' in position 0: ordinal not in range(128)\n\nIn [8]: '%s' % x\nOut[8]: u'\\u05d33\\u05d6\\u05e3\\u05d6\\u05dd\\u05e1\\u05e6\\u05e0\\u05d0'\n```\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/19852038",
    "html_url": "https://github.com/pandas-dev/pandas/issues/3919#issuecomment-19852038",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/3919",
    "id": 19852038,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE5ODUyMDM4",
    "user": {
      "login": "jtratner",
      "id": 1598379,
      "node_id": "MDQ6VXNlcjE1OTgzNzk=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1598379?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jtratner",
      "html_url": "https://github.com/jtratner",
      "followers_url": "https://api.github.com/users/jtratner/followers",
      "following_url": "https://api.github.com/users/jtratner/following{/other_user}",
      "gists_url": "https://api.github.com/users/jtratner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jtratner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jtratner/subscriptions",
      "organizations_url": "https://api.github.com/users/jtratner/orgs",
      "repos_url": "https://api.github.com/users/jtratner/repos",
      "events_url": "https://api.github.com/users/jtratner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jtratner/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-06-22T06:24:36Z",
    "updated_at": "2013-06-22T06:24:36Z",
    "author_association": "CONTRIBUTOR",
    "body": "weird...so does that barf when ipython tries to print the error?\n\nOn Fri, Jun 21, 2013 at 11:25 PM, Phillip Cloud notifications@github.comwrote:\n\n> not necessarily:\n> \n> In [4]: mkdf(1, 1, c_idx_type='u').columns[0]\n> Out[4]: u'1\\u05dd\\u05de3\\u05e4\\u05d2\\u05d47\\u05e3\\u05da'\n> \n> In [5]: x = mkdf(1, 1, c_idx_type='u').columns[0]\n> \n> ## In [6]: str(x)\n> \n> UnicodeEncodeError                        Traceback (most recent call last)\n> <ipython-input-6-68e10e3ad351> in <module>()\n> ----> 1 str(x)\n> \n> UnicodeEncodeError: 'ascii' codec can't encode character u'\\u05d3' in position 0: ordinal not in range(128)\n> \n> ## In [7]: '%s' % s\n> \n> NameError                                 Traceback (most recent call last)\n> <ipython-input-7-830b68e15a45> in <module>()\n> ----> 1 '%s' % s\n> \n> NameError: name 's' is not defined\n> \n> In [8]: '%s' % x\n> Out[8]: u'\\u05d33\\u05d6\\u05e3\\u05d6\\u05dd\\u05e1\\u05e6\\u05e0\\u05d0'\n> \n> â€”\n> Reply to this email directly or view it on GitHubhttps://github.com/pydata/pandas/issues/3919#issuecomment-19849866\n> .\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/22270551",
    "html_url": "https://github.com/pandas-dev/pandas/issues/3919#issuecomment-22270551",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/3919",
    "id": 22270551,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyMjcwNTUx",
    "user": {
      "login": "cpcloud",
      "id": 417981,
      "node_id": "MDQ6VXNlcjQxNzk4MQ==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/417981?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/cpcloud",
      "html_url": "https://github.com/cpcloud",
      "followers_url": "https://api.github.com/users/cpcloud/followers",
      "following_url": "https://api.github.com/users/cpcloud/following{/other_user}",
      "gists_url": "https://api.github.com/users/cpcloud/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/cpcloud/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/cpcloud/subscriptions",
      "organizations_url": "https://api.github.com/users/cpcloud/orgs",
      "repos_url": "https://api.github.com/users/cpcloud/repos",
      "events_url": "https://api.github.com/users/cpcloud/events{/privacy}",
      "received_events_url": "https://api.github.com/users/cpcloud/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-07T17:58:11Z",
    "updated_at": "2013-08-07T17:58:11Z",
    "author_association": "MEMBER",
    "body": "this is a problem with Python 2 vs 3 bc you can't print exceptions with unicode in python 2\n\n``` python\nraise ValueError('%s' % u'\\u2309')\n```\n"
  }
]
