[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/46684686",
    "html_url": "https://github.com/pandas-dev/pandas/issues/7524#issuecomment-46684686",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/7524",
    "id": 46684686,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2Njg0Njg2",
    "user": {
      "login": "davidastephens",
      "id": 5957850,
      "node_id": "MDQ6VXNlcjU5NTc4NTA=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/5957850?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/davidastephens",
      "html_url": "https://github.com/davidastephens",
      "followers_url": "https://api.github.com/users/davidastephens/followers",
      "following_url": "https://api.github.com/users/davidastephens/following{/other_user}",
      "gists_url": "https://api.github.com/users/davidastephens/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/davidastephens/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/davidastephens/subscriptions",
      "organizations_url": "https://api.github.com/users/davidastephens/orgs",
      "repos_url": "https://api.github.com/users/davidastephens/repos",
      "events_url": "https://api.github.com/users/davidastephens/events{/privacy}",
      "received_events_url": "https://api.github.com/users/davidastephens/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-06-20T14:33:31Z",
    "updated_at": "2014-06-20T14:33:31Z",
    "author_association": "CONTRIBUTOR",
    "body": "Agreed on the first one, I will add the try, except.\n\nThe second one is more strange, we discussed in #7392 that we should have it fail if it found some tables, but no the right one.  Otherwise you'd have no idea from the tests if Yahoo changed their formatting around.  \n\nI wonder if this is related somehow to expiry day.  I'll run the tests on my computer and see if they pass.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/46684983",
    "html_url": "https://github.com/pandas-dev/pandas/issues/7524#issuecomment-46684983",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/7524",
    "id": 46684983,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ2Njg0OTgz",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-06-20T14:36:00Z",
    "updated_at": "2014-06-20T14:36:00Z",
    "author_association": "CONTRIBUTOR",
    "body": "this is the first time that I saw this fail at all, so prob random....\n"
  }
]
