[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/73321344",
    "html_url": "https://github.com/pandas-dev/pandas/issues/9438#issuecomment-73321344",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/9438",
    "id": 73321344,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczMzIxMzQ0",
    "user": {
      "login": "jmatejka",
      "id": 1493341,
      "node_id": "MDQ6VXNlcjE0OTMzNDE=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1493341?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jmatejka",
      "html_url": "https://github.com/jmatejka",
      "followers_url": "https://api.github.com/users/jmatejka/followers",
      "following_url": "https://api.github.com/users/jmatejka/following{/other_user}",
      "gists_url": "https://api.github.com/users/jmatejka/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jmatejka/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jmatejka/subscriptions",
      "organizations_url": "https://api.github.com/users/jmatejka/orgs",
      "repos_url": "https://api.github.com/users/jmatejka/repos",
      "events_url": "https://api.github.com/users/jmatejka/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jmatejka/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-06T22:05:16Z",
    "updated_at": "2015-02-06T22:05:16Z",
    "author_association": "NONE",
    "body": "For what it's worth, the following is a workaround which seems to be doing the trick:\n\n```\nf = open(u\"C:/成功例Q309~Metadata.tsv\")\ndf = pd.read_csv(f)\nf.close()\n```\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/73880310",
    "html_url": "https://github.com/pandas-dev/pandas/issues/9438#issuecomment-73880310",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/9438",
    "id": 73880310,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczODgwMzEw",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-11T13:27:37Z",
    "updated_at": "2015-02-11T13:27:37Z",
    "author_association": "CONTRIBUTOR",
    "body": "see this issue here: https://github.com/pydata/pandas/issues/6770\n\nThis is already in 0.15.2 (e.g. it will decode with the system encoding). So I think you maybe need to set it.\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/73941230",
    "html_url": "https://github.com/pandas-dev/pandas/issues/9438#issuecomment-73941230",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/9438",
    "id": 73941230,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczOTQxMjMw",
    "user": {
      "login": "jmatejka",
      "id": 1493341,
      "node_id": "MDQ6VXNlcjE0OTMzNDE=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1493341?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jmatejka",
      "html_url": "https://github.com/jmatejka",
      "followers_url": "https://api.github.com/users/jmatejka/followers",
      "following_url": "https://api.github.com/users/jmatejka/following{/other_user}",
      "gists_url": "https://api.github.com/users/jmatejka/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jmatejka/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jmatejka/subscriptions",
      "organizations_url": "https://api.github.com/users/jmatejka/orgs",
      "repos_url": "https://api.github.com/users/jmatejka/repos",
      "events_url": "https://api.github.com/users/jmatejka/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jmatejka/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-11T18:59:13Z",
    "updated_at": "2015-02-11T18:59:13Z",
    "author_association": "NONE",
    "body": "My mistake, I am using 0.15.2 (not 15.1).\n\nBut I'm still not clear, what are you suggesting that I \"set\"? The system encoding? This is something that I would need to do before loading the file?\n\nThanks, Justin\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/73941573",
    "html_url": "https://github.com/pandas-dev/pandas/issues/9438#issuecomment-73941573",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/9438",
    "id": 73941573,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczOTQxNTcz",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-11T19:00:54Z",
    "updated_at": "2015-02-11T19:00:54Z",
    "author_association": "CONTRIBUTOR",
    "body": "I think the system encoding might be set to something odd\n\nyou can try setting to utf-8 and see if it works\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/73944165",
    "html_url": "https://github.com/pandas-dev/pandas/issues/9438#issuecomment-73944165",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/9438",
    "id": 73944165,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczOTQ0MTY1",
    "user": {
      "login": "jmatejka",
      "id": 1493341,
      "node_id": "MDQ6VXNlcjE0OTMzNDE=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1493341?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jmatejka",
      "html_url": "https://github.com/jmatejka",
      "followers_url": "https://api.github.com/users/jmatejka/followers",
      "following_url": "https://api.github.com/users/jmatejka/following{/other_user}",
      "gists_url": "https://api.github.com/users/jmatejka/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jmatejka/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jmatejka/subscriptions",
      "organizations_url": "https://api.github.com/users/jmatejka/orgs",
      "repos_url": "https://api.github.com/users/jmatejka/repos",
      "events_url": "https://api.github.com/users/jmatejka/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jmatejka/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-11T19:13:55Z",
    "updated_at": "2015-02-11T19:13:55Z",
    "author_association": "NONE",
    "body": "The filesystemencoding and defaultsystemencoding are 'mbcs' and 'cp1252' respectively:\n\n```\nsys.getfilesystemencoding()\nOut[12]: 'mbcs'\n\nsys.getdefaultencoding()\nOut[13]: 'cp1252'\n```\n\nThese options all fail in a similar way though:\n\n```\ndf = pandas.read_csv(u\"C:/成功例Q309~Metadata.tsv\", encoding='utf-8')\ndf = pandas.read_csv(u\"C:/成功例Q309~Metadata.tsv\", encoding='mbcs')\ndf = pandas.read_csv(u\"C:/成功例Q309~Metadata.tsv\", encoding='cp1252')\n```\n\nShould I bet setting the encoding in a different way?\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/73945314",
    "html_url": "https://github.com/pandas-dev/pandas/issues/9438#issuecomment-73945314",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/9438",
    "id": 73945314,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczOTQ1MzE0",
    "user": {
      "login": "jreback",
      "id": 953992,
      "node_id": "MDQ6VXNlcjk1Mzk5Mg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/953992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jreback",
      "html_url": "https://github.com/jreback",
      "followers_url": "https://api.github.com/users/jreback/followers",
      "following_url": "https://api.github.com/users/jreback/following{/other_user}",
      "gists_url": "https://api.github.com/users/jreback/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jreback/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jreback/subscriptions",
      "organizations_url": "https://api.github.com/users/jreback/orgs",
      "repos_url": "https://api.github.com/users/jreback/repos",
      "events_url": "https://api.github.com/users/jreback/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jreback/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-11T19:19:59Z",
    "updated_at": "2015-02-11T19:19:59Z",
    "author_association": "CONTRIBUTOR",
    "body": "these have to do with the encoding of the file itself not the filename\ntry decoding that filename before passing\n\neg\n\nthe_filename.decode('utf-8') then pass the filename\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/73965400",
    "html_url": "https://github.com/pandas-dev/pandas/issues/9438#issuecomment-73965400",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/9438",
    "id": 73965400,
    "node_id": "MDEyOklzc3VlQ29tbWVudDczOTY1NDAw",
    "user": {
      "login": "jmatejka",
      "id": 1493341,
      "node_id": "MDQ6VXNlcjE0OTMzNDE=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1493341?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jmatejka",
      "html_url": "https://github.com/jmatejka",
      "followers_url": "https://api.github.com/users/jmatejka/followers",
      "following_url": "https://api.github.com/users/jmatejka/following{/other_user}",
      "gists_url": "https://api.github.com/users/jmatejka/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jmatejka/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jmatejka/subscriptions",
      "organizations_url": "https://api.github.com/users/jmatejka/orgs",
      "repos_url": "https://api.github.com/users/jmatejka/repos",
      "events_url": "https://api.github.com/users/jmatejka/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jmatejka/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-02-11T21:10:10Z",
    "updated_at": "2015-02-11T21:10:10Z",
    "author_association": "NONE",
    "body": "Using `filename.decode('utf'8')` gives this error:\n\n```\n\nUnicodeEncodeError: 'charmap' codec can't encode characters in position 3-5: character maps to <undefined>\n```\n"
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/313884134",
    "html_url": "https://github.com/pandas-dev/pandas/issues/9438#issuecomment-313884134",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/9438",
    "id": 313884134,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMxMzg4NDEzNA==",
    "user": {
      "login": "TomAugspurger",
      "id": 1312546,
      "node_id": "MDQ6VXNlcjEzMTI1NDY=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1312546?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/TomAugspurger",
      "html_url": "https://github.com/TomAugspurger",
      "followers_url": "https://api.github.com/users/TomAugspurger/followers",
      "following_url": "https://api.github.com/users/TomAugspurger/following{/other_user}",
      "gists_url": "https://api.github.com/users/TomAugspurger/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/TomAugspurger/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/TomAugspurger/subscriptions",
      "organizations_url": "https://api.github.com/users/TomAugspurger/orgs",
      "repos_url": "https://api.github.com/users/TomAugspurger/repos",
      "events_url": "https://api.github.com/users/TomAugspurger/events{/privacy}",
      "received_events_url": "https://api.github.com/users/TomAugspurger/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-07-08T22:15:23Z",
    "updated_at": "2017-07-08T22:15:23Z",
    "author_association": "CONTRIBUTOR",
    "body": "I think this is an issue with the filesystem / encoding. Let me know if it's still a problem, and if Python's builtin `open(filename)` works, but pandas `read_csv` does not."
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/comments/431866113",
    "html_url": "https://github.com/pandas-dev/pandas/issues/9438#issuecomment-431866113",
    "issue_url": "https://api.github.com/repos/pandas-dev/pandas/issues/9438",
    "id": 431866113,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQzMTg2NjExMw==",
    "user": {
      "login": "Masterxilo",
      "id": 2378665,
      "node_id": "MDQ6VXNlcjIzNzg2NjU=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/2378665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Masterxilo",
      "html_url": "https://github.com/Masterxilo",
      "followers_url": "https://api.github.com/users/Masterxilo/followers",
      "following_url": "https://api.github.com/users/Masterxilo/following{/other_user}",
      "gists_url": "https://api.github.com/users/Masterxilo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Masterxilo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Masterxilo/subscriptions",
      "organizations_url": "https://api.github.com/users/Masterxilo/orgs",
      "repos_url": "https://api.github.com/users/Masterxilo/repos",
      "events_url": "https://api.github.com/users/Masterxilo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Masterxilo/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-10-22T15:19:08Z",
    "updated_at": "2018-10-22T15:19:08Z",
    "author_association": "NONE",
    "body": "This still happens for me. The worst part is that if I use the workaround using `open`, read_csv does not parse the utf-8 in the file correctly anymore. Any help?"
  }
]
