[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/381423429",
    "html_url": "https://github.com/ipython/ipython/issues/11097#issuecomment-381423429",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/11097",
    "id": 381423429,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4MTQyMzQyOQ==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-15T17:31:20Z",
    "updated_at": "2018-04-15T17:31:20Z",
    "author_association": "MEMBER",
    "body": "I think you'll need to ask spacy about that, at least at first. Jupyter doesn't understand enough about the code you're running to be the direct cause of a problem like that."
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/384956324",
    "html_url": "https://github.com/ipython/ipython/issues/11097#issuecomment-384956324",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/11097",
    "id": 384956324,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM4NDk1NjMyNA==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-27T12:32:27Z",
    "updated_at": "2018-04-27T12:32:27Z",
    "author_association": "MEMBER",
    "body": "Follow up with spacy: https://github.com/explosion/spaCy/issues/2225"
  }
]
