[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22067907",
    "html_url": "https://github.com/ipython/ipython/issues/3884#issuecomment-22067907",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/3884",
    "id": 22067907,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyMDY3OTA3",
    "user": {
      "login": "ivanov",
      "id": 118211,
      "node_id": "MDQ6VXNlcjExODIxMQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/118211?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanov",
      "html_url": "https://github.com/ivanov",
      "followers_url": "https://api.github.com/users/ivanov/followers",
      "following_url": "https://api.github.com/users/ivanov/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanov/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanov/orgs",
      "repos_url": "https://api.github.com/users/ivanov/repos",
      "events_url": "https://api.github.com/users/ivanov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanov/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-04T07:18:55Z",
    "updated_at": "2013-08-04T07:18:55Z",
    "author_association": "MEMBER",
    "body": "are you running this in plain old `ipython`? I'm unable to reproduce this one on master (all 1000 iterations run just fine). Can you try [1.0.0rc1](http://archive.ipython.org/testing/1.0.0/) to see if that fixes the issue for you?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22067947",
    "html_url": "https://github.com/ipython/ipython/issues/3884#issuecomment-22067947",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/3884",
    "id": 22067947,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyMDY3OTQ3",
    "user": {
      "login": "ivanov",
      "id": 118211,
      "node_id": "MDQ6VXNlcjExODIxMQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/118211?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanov",
      "html_url": "https://github.com/ivanov",
      "followers_url": "https://api.github.com/users/ivanov/followers",
      "following_url": "https://api.github.com/users/ivanov/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanov/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanov/orgs",
      "repos_url": "https://api.github.com/users/ivanov/repos",
      "events_url": "https://api.github.com/users/ivanov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanov/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-04T07:23:27Z",
    "updated_at": "2013-08-04T07:23:27Z",
    "author_association": "MEMBER",
    "body": "As another point of reference, I tried running your example on a checkout of 0.13.2 and it works just fine there, as well.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22068732",
    "html_url": "https://github.com/ipython/ipython/issues/3884#issuecomment-22068732",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/3884",
    "id": 22068732,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyMDY4NzMy",
    "user": {
      "login": "lucacerone",
      "id": 754360,
      "node_id": "MDQ6VXNlcjc1NDM2MA==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/754360?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucacerone",
      "html_url": "https://github.com/lucacerone",
      "followers_url": "https://api.github.com/users/lucacerone/followers",
      "following_url": "https://api.github.com/users/lucacerone/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucacerone/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucacerone/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucacerone/subscriptions",
      "organizations_url": "https://api.github.com/users/lucacerone/orgs",
      "repos_url": "https://api.github.com/users/lucacerone/repos",
      "events_url": "https://api.github.com/users/lucacerone/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucacerone/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-04T08:56:50Z",
    "updated_at": "2013-08-04T08:56:50Z",
    "author_association": "NONE",
    "body": "Hi Ivanov,\nthanks for the efforts! (I am sorry if I didn't provide complete information, I am relatively new to ipython)\n\nYou are right opening only ipython and typing the commands I posted above does not cause the issue.\nHowever the bug exists if I open it using \"ipython --pylab\" from the shell (which I have experienced on different computers).. I forgot about the option because I always run pylab together with ipython, since I do a lot of scientific computing, and I have an alias for it.. I don't know if it can help, I also use the QT4Agg backend for matplotlib, which I have set in the matplotlibrc file). \n\nIf you explain me how I can use the release candidate in a virtual environment (I don't want to mess up my default\ninstallation.. is it enough that I create the virtual environment copy the code in the lib folder and run it from there??\n\nThanks again,\nLuca\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22069114",
    "html_url": "https://github.com/ipython/ipython/issues/3884#issuecomment-22069114",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/3884",
    "id": 22069114,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyMDY5MTE0",
    "user": {
      "login": "lucacerone",
      "id": 754360,
      "node_id": "MDQ6VXNlcjc1NDM2MA==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/754360?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucacerone",
      "html_url": "https://github.com/lucacerone",
      "followers_url": "https://api.github.com/users/lucacerone/followers",
      "following_url": "https://api.github.com/users/lucacerone/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucacerone/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucacerone/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucacerone/subscriptions",
      "organizations_url": "https://api.github.com/users/lucacerone/orgs",
      "repos_url": "https://api.github.com/users/lucacerone/repos",
      "events_url": "https://api.github.com/users/lucacerone/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucacerone/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-04T09:37:11Z",
    "updated_at": "2013-08-04T09:37:11Z",
    "author_association": "NONE",
    "body": "Hi Ivanov, \nI can confirm that the issue arise with version 1.0.0-rc1 using the --pylab option.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22072767",
    "html_url": "https://github.com/ipython/ipython/issues/3884#issuecomment-22072767",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/3884",
    "id": 22072767,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyMDcyNzY3",
    "user": {
      "login": "ivanov",
      "id": 118211,
      "node_id": "MDQ6VXNlcjExODIxMQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/118211?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanov",
      "html_url": "https://github.com/ivanov",
      "followers_url": "https://api.github.com/users/ivanov/followers",
      "following_url": "https://api.github.com/users/ivanov/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanov/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanov/orgs",
      "repos_url": "https://api.github.com/users/ivanov/repos",
      "events_url": "https://api.github.com/users/ivanov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanov/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-04T14:41:36Z",
    "updated_at": "2013-08-04T14:43:00Z",
    "author_association": "MEMBER",
    "body": "ok, i can confirm the behavior with --pylab flag, but you're running into a buffering issue:\n\n> Warning Use communicate() rather than .stdin.write, .stdout.read or .stderr.read to avoid deadlocks due to any of the other OS pipe buffers filling up and blocking the child process.\n\nhttp://docs.python.org/2/library/subprocess.html#subprocess.Popen.kill\n\nchange your code to use communicate(), which returns a (stdout, stderr) tuple like so:\n\n```\ndef dummyfun():\n        p1 = sp.Popen(['ls','-lah'], stderr=sp.STDOUT, stdout=sp.PIPE, close_fds=True)\n        p2 = sp.Popen(['grep','.'],stdin=p1.stdout, stdout=sp.PIPE, close_fds=True)\n        _,_ = p1.communicate();\n        return p2.communicate()[0]\n\ndef dummyfun3():\n        fo = dummyfun()\n        dummyfun2(fo)\n```\n\nwith that change, I don't see an IOError anymore\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22075144",
    "html_url": "https://github.com/ipython/ipython/issues/3884#issuecomment-22075144",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/3884",
    "id": 22075144,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyMDc1MTQ0",
    "user": {
      "login": "lucacerone",
      "id": 754360,
      "node_id": "MDQ6VXNlcjc1NDM2MA==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/754360?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucacerone",
      "html_url": "https://github.com/lucacerone",
      "followers_url": "https://api.github.com/users/lucacerone/followers",
      "following_url": "https://api.github.com/users/lucacerone/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucacerone/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucacerone/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucacerone/subscriptions",
      "organizations_url": "https://api.github.com/users/lucacerone/orgs",
      "repos_url": "https://api.github.com/users/lucacerone/repos",
      "events_url": "https://api.github.com/users/lucacerone/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucacerone/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-04T17:17:15Z",
    "updated_at": "2013-08-04T17:17:15Z",
    "author_association": "NONE",
    "body": "Hi Ivanov,\nactually as I explained this was just an example, to show what the issue is.\nIn my real code, I can't use communicate:\n\n> communicate() returns a tuple (stdoutdata, stderrdata).\n> \n> Note that if you want to send data to the process’s stdin, you need to create the Popen object with stdin=PIPE. > Similarly, to get anything other than None in the result tuple, you need to give stdout=PIPE and/or stderr=PIPE > too.\n> \n> Note The data read is buffered in memory, so do not use this method if the data size is large or unlimited.\n\nIn my real code the output of the dummyfun function is usually as large as 4-5gb.. sometimes more (it is produced by external tools, I have no control over it) that's why I can not use communicate(). dummyfun2 actually is a parser for the output of dummyfun that goes line by line to extract the relevant features. The dummyfun3 is just a wrapper that I use to tie all of the things together and hide the details from the users. \nSince it is for a scientific package I think it is sound to assume that the users will use pylab.. \n\nI can't see to find any alternative to my code that doesn't use communicate... what would be the best way to deal with this issue? Can you link me to some resource? And why this does not arise without using pylab? I ask just to understand better where potential issues can arise and how to fix them!\n\nThanks for the help!\nLuca\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22077758",
    "html_url": "https://github.com/ipython/ipython/issues/3884#issuecomment-22077758",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/3884",
    "id": 22077758,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyMDc3NzU4",
    "user": {
      "login": "ivanov",
      "id": 118211,
      "node_id": "MDQ6VXNlcjExODIxMQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/118211?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanov",
      "html_url": "https://github.com/ivanov",
      "followers_url": "https://api.github.com/users/ivanov/followers",
      "following_url": "https://api.github.com/users/ivanov/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanov/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanov/orgs",
      "repos_url": "https://api.github.com/users/ivanov/repos",
      "events_url": "https://api.github.com/users/ivanov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanov/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-04T19:59:40Z",
    "updated_at": "2013-08-04T19:59:40Z",
    "author_association": "MEMBER",
    "body": "Ok, Luca, re-opening based on your updated description.\n\nWhat `--pylab` does (which we're now actually transitioning to just be `--matplotlib`) is enable the GUI event loop integration, and set up matplotlib to use it. There are several GUI toolkits supported, and depending on what you have available on your system, you should try a different one to see if that fixes the issue for you. For example, on my machine, `Qt` is used as the default and I see the error you originally reported, but if I specify `--pylab=wx`, `--pylab=gtk` or `--pylab=tk` I don't see the error.\n\nIf that still doesn't work, or as an alternative to using Popen, I suggest looking into using [Named Pipes](http://en.wikipedia.org/wiki/Named_pipe), (using `os.mkfifo`) and dealing with the communication as though it was a file.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22077869",
    "html_url": "https://github.com/ipython/ipython/issues/3884#issuecomment-22077869",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/3884",
    "id": 22077869,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyMDc3ODY5",
    "user": {
      "login": "ivanov",
      "id": 118211,
      "node_id": "MDQ6VXNlcjExODIxMQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/118211?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ivanov",
      "html_url": "https://github.com/ivanov",
      "followers_url": "https://api.github.com/users/ivanov/followers",
      "following_url": "https://api.github.com/users/ivanov/following{/other_user}",
      "gists_url": "https://api.github.com/users/ivanov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ivanov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ivanov/subscriptions",
      "organizations_url": "https://api.github.com/users/ivanov/orgs",
      "repos_url": "https://api.github.com/users/ivanov/repos",
      "events_url": "https://api.github.com/users/ivanov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ivanov/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-04T20:06:00Z",
    "updated_at": "2013-08-04T20:06:00Z",
    "author_association": "MEMBER",
    "body": "Based on the fact that this only happens with one type of GUI (qt), I'm gonna leave this as a possible bug for now. It could just be somehow a limitation of Qt, but maybe there's something we can do on our end to make this not happen. In either case, we won't get to this until after 1.0, so marking it as 2.0 material. You should use one of the workarounds I suggested until then (or perhaps someone else will chime in with another one).\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/22080066",
    "html_url": "https://github.com/ipython/ipython/issues/3884#issuecomment-22080066",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/3884",
    "id": 22080066,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyMDgwMDY2",
    "user": {
      "login": "lucacerone",
      "id": 754360,
      "node_id": "MDQ6VXNlcjc1NDM2MA==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/754360?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lucacerone",
      "html_url": "https://github.com/lucacerone",
      "followers_url": "https://api.github.com/users/lucacerone/followers",
      "following_url": "https://api.github.com/users/lucacerone/following{/other_user}",
      "gists_url": "https://api.github.com/users/lucacerone/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lucacerone/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lucacerone/subscriptions",
      "organizations_url": "https://api.github.com/users/lucacerone/orgs",
      "repos_url": "https://api.github.com/users/lucacerone/repos",
      "events_url": "https://api.github.com/users/lucacerone/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lucacerone/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-08-04T22:10:52Z",
    "updated_at": "2013-08-04T22:10:52Z",
    "author_association": "NONE",
    "body": "Thanks for all the help Ivanov. I dig a bit into it because since I am relatively new to Python, I couldn't figure if I was doing something wrong or not. For the moment I will try to setup a different GUI environment so that I can finish the development of my package. If I get to know (asking to forums for Qt) what a possible solution workaround can be I will let you know, just in case that might help!\n\nThanks a lot again for all the helps and explanations!\n"
  }
]
