[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/28503950",
    "html_url": "https://github.com/ipython/ipython/issues/4537#issuecomment-28503950",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4537",
    "id": 28503950,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI4NTAzOTUw",
    "user": {
      "login": "jdfreder",
      "id": 3292874,
      "node_id": "MDQ6VXNlcjMyOTI4NzQ=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3292874?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jdfreder",
      "html_url": "https://github.com/jdfreder",
      "followers_url": "https://api.github.com/users/jdfreder/followers",
      "following_url": "https://api.github.com/users/jdfreder/following{/other_user}",
      "gists_url": "https://api.github.com/users/jdfreder/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jdfreder/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jdfreder/subscriptions",
      "organizations_url": "https://api.github.com/users/jdfreder/orgs",
      "repos_url": "https://api.github.com/users/jdfreder/repos",
      "events_url": "https://api.github.com/users/jdfreder/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jdfreder/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-11-14T17:25:44Z",
    "updated_at": "2013-11-14T17:25:44Z",
    "author_association": "MEMBER",
    "body": "Hi David,\n\nThe book template now inherits from LaTeX report so it is named `report`.  Sphinx output was dropped because of the complication between it and mdframed.  Later it was decided to drop mdframed too.  See https://github.com/ipython/ipython/pull/4112\n\nThe book file you point to doesn't exist in master.  My guess is that the directory you pointed to is stale.  If you still want to use the Sphinx template, it has been fixed and moved to the examples repository - https://github.com/ipython/nbconvert-examples .  There you can also see how to change cell style etc... (A new concept with 2.0)\n\nSorry for the troubles and I hope this helps,\n\nJonathan\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/28513638",
    "html_url": "https://github.com/ipython/ipython/issues/4537#issuecomment-28513638",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4537",
    "id": 28513638,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI4NTEzNjM4",
    "user": {
      "login": "dpsanders",
      "id": 191822,
      "node_id": "MDQ6VXNlcjE5MTgyMg==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/191822?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dpsanders",
      "html_url": "https://github.com/dpsanders",
      "followers_url": "https://api.github.com/users/dpsanders/followers",
      "following_url": "https://api.github.com/users/dpsanders/following{/other_user}",
      "gists_url": "https://api.github.com/users/dpsanders/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dpsanders/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dpsanders/subscriptions",
      "organizations_url": "https://api.github.com/users/dpsanders/orgs",
      "repos_url": "https://api.github.com/users/dpsanders/repos",
      "events_url": "https://api.github.com/users/dpsanders/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dpsanders/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-11-14T19:19:08Z",
    "updated_at": "2013-11-14T19:19:08Z",
    "author_association": "CONTRIBUTOR",
    "body": "Hi Jon,\n\nSorry, I hadn't kept up with the news.\nI'll have a look at the examples.\n\nThanks,\nDavid.\n\nPS: I seem to have trouble with filenames which contain accented letters. Is this a bug or a feature? ;)\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/28514016",
    "html_url": "https://github.com/ipython/ipython/issues/4537#issuecomment-28514016",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4537",
    "id": 28514016,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI4NTE0MDE2",
    "user": {
      "login": "jdfreder",
      "id": 3292874,
      "node_id": "MDQ6VXNlcjMyOTI4NzQ=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3292874?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jdfreder",
      "html_url": "https://github.com/jdfreder",
      "followers_url": "https://api.github.com/users/jdfreder/followers",
      "following_url": "https://api.github.com/users/jdfreder/following{/other_user}",
      "gists_url": "https://api.github.com/users/jdfreder/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jdfreder/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jdfreder/subscriptions",
      "organizations_url": "https://api.github.com/users/jdfreder/orgs",
      "repos_url": "https://api.github.com/users/jdfreder/repos",
      "events_url": "https://api.github.com/users/jdfreder/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jdfreder/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2013-11-14T19:23:01Z",
    "updated_at": "2013-11-14T19:23:01Z",
    "author_association": "MEMBER",
    "body": ">  Is this a bug or a feature? ;)\n\nNow that sounds like a bug. :stuck_out_tongue:   Could you either open an issue for that or paste the offending file name(s) here so I can open an issue?  I'm going to close this issue ...\n\nPS. I'm not sure what the first two warnings are in the error you posted.  Maybe something missing/garbled in the Python installation?\n"
  }
]
