[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/33261893",
    "html_url": "https://github.com/ipython/ipython/pull/4866#issuecomment-33261893",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4866",
    "id": 33261893,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMzMjYxODkz",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-01-24T21:14:50Z",
    "updated_at": "2014-01-24T21:14:50Z",
    "author_association": "MEMBER",
    "body": "I don't see what in the changes prevents the exception printing that you\nsay happens at present. Am I missing something?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/33271751",
    "html_url": "https://github.com/ipython/ipython/pull/4866#issuecomment-33271751",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4866",
    "id": 33271751,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMzMjcxNzUx",
    "user": {
      "login": "ghost",
      "id": 10137,
      "node_id": "MDQ6VXNlcjEwMTM3",
      "avatar_url": "https://avatars3.githubusercontent.com/u/10137?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ghost",
      "html_url": "https://github.com/ghost",
      "followers_url": "https://api.github.com/users/ghost/followers",
      "following_url": "https://api.github.com/users/ghost/following{/other_user}",
      "gists_url": "https://api.github.com/users/ghost/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ghost/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ghost/subscriptions",
      "organizations_url": "https://api.github.com/users/ghost/orgs",
      "repos_url": "https://api.github.com/users/ghost/repos",
      "events_url": "https://api.github.com/users/ghost/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ghost/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-01-24T23:28:12Z",
    "updated_at": "2014-01-24T23:28:12Z",
    "author_association": "NONE",
    "body": "And with that realization, I now see that the maddening lack of context when errors\nare output to the console is not due to the original ipython_directive, but this addition\nto it.\nI do not wish to inflict that on others. Will try again when I have time to dive in to\nsphinx extension land.\n\nApologies for the noise.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/33272608",
    "html_url": "https://github.com/ipython/ipython/pull/4866#issuecomment-33272608",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4866",
    "id": 33272608,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMzMjcyNjA4",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-01-24T23:44:15Z",
    "updated_at": "2014-01-24T23:44:15Z",
    "author_association": "MEMBER",
    "body": "OK, no worries.\n"
  }
]
