[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/33467259",
    "html_url": "https://github.com/ipython/ipython/issues/4898#issuecomment-33467259",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4898",
    "id": 33467259,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMzNDY3MjU5",
    "user": {
      "login": "stefanv",
      "id": 45071,
      "node_id": "MDQ6VXNlcjQ1MDcx",
      "avatar_url": "https://avatars2.githubusercontent.com/u/45071?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stefanv",
      "html_url": "https://github.com/stefanv",
      "followers_url": "https://api.github.com/users/stefanv/followers",
      "following_url": "https://api.github.com/users/stefanv/following{/other_user}",
      "gists_url": "https://api.github.com/users/stefanv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stefanv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stefanv/subscriptions",
      "organizations_url": "https://api.github.com/users/stefanv/orgs",
      "repos_url": "https://api.github.com/users/stefanv/repos",
      "events_url": "https://api.github.com/users/stefanv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stefanv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-01-28T10:37:57Z",
    "updated_at": "2014-01-28T10:37:57Z",
    "author_association": "CONTRIBUTOR",
    "body": "/cc @damianavila\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/33474304",
    "html_url": "https://github.com/ipython/ipython/issues/4898#issuecomment-33474304",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4898",
    "id": 33474304,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMzNDc0MzA0",
    "user": {
      "login": "damianavila",
      "id": 1640669,
      "node_id": "MDQ6VXNlcjE2NDA2Njk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1640669?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/damianavila",
      "html_url": "https://github.com/damianavila",
      "followers_url": "https://api.github.com/users/damianavila/followers",
      "following_url": "https://api.github.com/users/damianavila/following{/other_user}",
      "gists_url": "https://api.github.com/users/damianavila/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/damianavila/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/damianavila/subscriptions",
      "organizations_url": "https://api.github.com/users/damianavila/orgs",
      "repos_url": "https://api.github.com/users/damianavila/repos",
      "events_url": "https://api.github.com/users/damianavila/events{/privacy}",
      "received_events_url": "https://api.github.com/users/damianavila/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-01-28T12:34:24Z",
    "updated_at": "2014-01-28T12:34:24Z",
    "author_association": "MEMBER",
    "body": "Which version of IPython are you trying?\nI can not reproduce it with current master... I see the subitem as a new level...\n\n![nested](https://f.cloud.github.com/assets/1640669/2018915/59c36836-8818-11e3-8c81-ffa5d57b0e1a.png)\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/33497158",
    "html_url": "https://github.com/ipython/ipython/issues/4898#issuecomment-33497158",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4898",
    "id": 33497158,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMzNDk3MTU4",
    "user": {
      "login": "stefanv",
      "id": 45071,
      "node_id": "MDQ6VXNlcjQ1MDcx",
      "avatar_url": "https://avatars2.githubusercontent.com/u/45071?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stefanv",
      "html_url": "https://github.com/stefanv",
      "followers_url": "https://api.github.com/users/stefanv/followers",
      "following_url": "https://api.github.com/users/stefanv/following{/other_user}",
      "gists_url": "https://api.github.com/users/stefanv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stefanv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stefanv/subscriptions",
      "organizations_url": "https://api.github.com/users/stefanv/orgs",
      "repos_url": "https://api.github.com/users/stefanv/repos",
      "events_url": "https://api.github.com/users/stefanv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stefanv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-01-28T16:47:06Z",
    "updated_at": "2014-01-28T16:47:06Z",
    "author_association": "CONTRIBUTOR",
    "body": "Strange, I pulled from master today.  Here's the notebook I am using:\n\nhttps://www.dropbox.com/s/9ab77f4f05toj34/slides_test.ipynb\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/33504706",
    "html_url": "https://github.com/ipython/ipython/issues/4898#issuecomment-33504706",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4898",
    "id": 33504706,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMzNTA0NzA2",
    "user": {
      "login": "damianavila",
      "id": 1640669,
      "node_id": "MDQ6VXNlcjE2NDA2Njk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1640669?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/damianavila",
      "html_url": "https://github.com/damianavila",
      "followers_url": "https://api.github.com/users/damianavila/followers",
      "following_url": "https://api.github.com/users/damianavila/following{/other_user}",
      "gists_url": "https://api.github.com/users/damianavila/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/damianavila/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/damianavila/subscriptions",
      "organizations_url": "https://api.github.com/users/damianavila/orgs",
      "repos_url": "https://api.github.com/users/damianavila/repos",
      "events_url": "https://api.github.com/users/damianavila/events{/privacy}",
      "received_events_url": "https://api.github.com/users/damianavila/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-01-28T17:53:52Z",
    "updated_at": "2014-01-28T17:53:52Z",
    "author_association": "MEMBER",
    "body": "I test your notebook and I get the same nested list.\n\nPlease try cleaning your cache or use incognito mode in Chrome... oh... which browser are you using to see the slides?\n\nImage from your notebook (NOTE: the cells are not centered because you did not label the cell as \"slide\"):\n\n![list](https://f.cloud.github.com/assets/1640669/2021853/f8ff0d0c-8844-11e3-986f-1710c1861e83.png)\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/34220031",
    "html_url": "https://github.com/ipython/ipython/issues/4898#issuecomment-34220031",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4898",
    "id": 34220031,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM0MjIwMDMx",
    "user": {
      "login": "ellisonbg",
      "id": 27600,
      "node_id": "MDQ6VXNlcjI3NjAw",
      "avatar_url": "https://avatars3.githubusercontent.com/u/27600?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ellisonbg",
      "html_url": "https://github.com/ellisonbg",
      "followers_url": "https://api.github.com/users/ellisonbg/followers",
      "following_url": "https://api.github.com/users/ellisonbg/following{/other_user}",
      "gists_url": "https://api.github.com/users/ellisonbg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ellisonbg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ellisonbg/subscriptions",
      "organizations_url": "https://api.github.com/users/ellisonbg/orgs",
      "repos_url": "https://api.github.com/users/ellisonbg/repos",
      "events_url": "https://api.github.com/users/ellisonbg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ellisonbg/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-02-05T18:19:52Z",
    "updated_at": "2014-02-05T18:19:52Z",
    "author_association": "MEMBER",
    "body": "@stefanv did clearing your cache fix this. If so, let's close it.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/34220762",
    "html_url": "https://github.com/ipython/ipython/issues/4898#issuecomment-34220762",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4898",
    "id": 34220762,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM0MjIwNzYy",
    "user": {
      "login": "stefanv",
      "id": 45071,
      "node_id": "MDQ6VXNlcjQ1MDcx",
      "avatar_url": "https://avatars2.githubusercontent.com/u/45071?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stefanv",
      "html_url": "https://github.com/stefanv",
      "followers_url": "https://api.github.com/users/stefanv/followers",
      "following_url": "https://api.github.com/users/stefanv/following{/other_user}",
      "gists_url": "https://api.github.com/users/stefanv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stefanv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stefanv/subscriptions",
      "organizations_url": "https://api.github.com/users/stefanv/orgs",
      "repos_url": "https://api.github.com/users/stefanv/repos",
      "events_url": "https://api.github.com/users/stefanv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stefanv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-02-05T18:27:03Z",
    "updated_at": "2014-02-05T18:27:03Z",
    "author_association": "CONTRIBUTOR",
    "body": "I still see this problem, even on an incognito window.  Can you also not\nreproduce this?\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/34434072",
    "html_url": "https://github.com/ipython/ipython/issues/4898#issuecomment-34434072",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4898",
    "id": 34434072,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM0NDM0MDcy",
    "user": {
      "login": "damianavila",
      "id": 1640669,
      "node_id": "MDQ6VXNlcjE2NDA2Njk=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/1640669?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/damianavila",
      "html_url": "https://github.com/damianavila",
      "followers_url": "https://api.github.com/users/damianavila/followers",
      "following_url": "https://api.github.com/users/damianavila/following{/other_user}",
      "gists_url": "https://api.github.com/users/damianavila/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/damianavila/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/damianavila/subscriptions",
      "organizations_url": "https://api.github.com/users/damianavila/orgs",
      "repos_url": "https://api.github.com/users/damianavila/repos",
      "events_url": "https://api.github.com/users/damianavila/events{/privacy}",
      "received_events_url": "https://api.github.com/users/damianavila/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-02-07T12:54:21Z",
    "updated_at": "2014-02-07T12:54:21Z",
    "author_association": "MEMBER",
    "body": "Can somebody else try to reproduce this... I tried but I am not getting the bug... Thanks.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/34483354",
    "html_url": "https://github.com/ipython/ipython/issues/4898#issuecomment-34483354",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4898",
    "id": 34483354,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM0NDgzMzU0",
    "user": {
      "login": "stefanv",
      "id": 45071,
      "node_id": "MDQ6VXNlcjQ1MDcx",
      "avatar_url": "https://avatars2.githubusercontent.com/u/45071?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stefanv",
      "html_url": "https://github.com/stefanv",
      "followers_url": "https://api.github.com/users/stefanv/followers",
      "following_url": "https://api.github.com/users/stefanv/following{/other_user}",
      "gists_url": "https://api.github.com/users/stefanv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stefanv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stefanv/subscriptions",
      "organizations_url": "https://api.github.com/users/stefanv/orgs",
      "repos_url": "https://api.github.com/users/stefanv/repos",
      "events_url": "https://api.github.com/users/stefanv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stefanv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-02-07T18:22:33Z",
    "updated_at": "2014-02-07T18:22:33Z",
    "author_association": "CONTRIBUTOR",
    "body": "I tried again today with a brand new pull of IPython.  I performed a \"git\nclean -xdf\", so hopefully that would take care of any old files lying\naround.  I then tried in an incognito window, as well as refreshing another\nbrowser window.  If it is clear that it is only me experiencing this\nproblem, then you can go ahead and close the bug.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/34483451",
    "html_url": "https://github.com/ipython/ipython/issues/4898#issuecomment-34483451",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4898",
    "id": 34483451,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM0NDgzNDUx",
    "user": {
      "login": "stefanv",
      "id": 45071,
      "node_id": "MDQ6VXNlcjQ1MDcx",
      "avatar_url": "https://avatars2.githubusercontent.com/u/45071?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stefanv",
      "html_url": "https://github.com/stefanv",
      "followers_url": "https://api.github.com/users/stefanv/followers",
      "following_url": "https://api.github.com/users/stefanv/following{/other_user}",
      "gists_url": "https://api.github.com/users/stefanv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stefanv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stefanv/subscriptions",
      "organizations_url": "https://api.github.com/users/stefanv/orgs",
      "repos_url": "https://api.github.com/users/stefanv/repos",
      "events_url": "https://api.github.com/users/stefanv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stefanv/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-02-07T18:23:38Z",
    "updated_at": "2014-02-07T18:23:38Z",
    "author_association": "CONTRIBUTOR",
    "body": "I've tried again with a new pull of IPython and a `git clean -xdf`.  Then\nI used an incognito window in the browser, as well as refreshing the\nnotebook several times.  If no-one else experiences this problem, then feel\nfree to close.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/34531055",
    "html_url": "https://github.com/ipython/ipython/issues/4898#issuecomment-34531055",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4898",
    "id": 34531055,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM0NTMxMDU1",
    "user": {
      "login": "ellisonbg",
      "id": 27600,
      "node_id": "MDQ6VXNlcjI3NjAw",
      "avatar_url": "https://avatars3.githubusercontent.com/u/27600?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ellisonbg",
      "html_url": "https://github.com/ellisonbg",
      "followers_url": "https://api.github.com/users/ellisonbg/followers",
      "following_url": "https://api.github.com/users/ellisonbg/following{/other_user}",
      "gists_url": "https://api.github.com/users/ellisonbg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ellisonbg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ellisonbg/subscriptions",
      "organizations_url": "https://api.github.com/users/ellisonbg/orgs",
      "repos_url": "https://api.github.com/users/ellisonbg/repos",
      "events_url": "https://api.github.com/users/ellisonbg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ellisonbg/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-02-08T03:27:46Z",
    "updated_at": "2014-02-08T03:27:46Z",
    "author_association": "MEMBER",
    "body": "Thanks Stefan, we will try to get to reproducing this one.\n\nOn Fri, Feb 7, 2014 at 10:23 AM, Stefan van der Walt <\nnotifications@github.com> wrote:\n\n> I've tried again with a new pull of IPython and a `git clean -xdf`. Then\n> I used an incognito window in the browser, as well as refreshing the\n> notebook several times. If no-one else experiences this problem, then feel\n> free to close.\n> \n> ## \n> \n> Reply to this email directly or view it on GitHubhttps://github.com/ipython/ipython/issues/4898#issuecomment-34483451\n> .\n\n## \n\nBrian E. Granger\nCal Poly State University, San Luis Obispo\nbgranger@calpoly.edu and ellisonbg@gmail.com\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/43371836",
    "html_url": "https://github.com/ipython/ipython/issues/4898#issuecomment-43371836",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/4898",
    "id": 43371836,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQzMzcxODM2",
    "user": {
      "login": "tyarkoni",
      "id": 303932,
      "node_id": "MDQ6VXNlcjMwMzkzMg==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/303932?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tyarkoni",
      "html_url": "https://github.com/tyarkoni",
      "followers_url": "https://api.github.com/users/tyarkoni/followers",
      "following_url": "https://api.github.com/users/tyarkoni/following{/other_user}",
      "gists_url": "https://api.github.com/users/tyarkoni/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tyarkoni/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tyarkoni/subscriptions",
      "organizations_url": "https://api.github.com/users/tyarkoni/orgs",
      "repos_url": "https://api.github.com/users/tyarkoni/repos",
      "events_url": "https://api.github.com/users/tyarkoni/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tyarkoni/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2014-05-16T19:45:15Z",
    "updated_at": "2014-05-16T19:45:15Z",
    "author_association": "NONE",
    "body": "A related issue: nested list items aren't handled correctly as fragments. I.e., suppose I want to have transitions not only between top-level list items, but also lower-level ones. I could add a fragment containing this markdown:\n\n```\n* a nested list item indented 4 spaces\n```\n\n...but this doesn't get interpreted as a nested list item, it's simply printed verbatim--presumably because the fragments aren't context-aware.\n\nIn practice, I'm working around this by programmatically wrapping each nested list item in <div class=\"fragment\"></div> tags, but I wonder if I'm missing some existing functionality, or if there's an easy fix to obtain the desired behavior?\n"
  }
]
