[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/128105754",
    "html_url": "https://github.com/ipython/ipython/issues/8689#issuecomment-128105754",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8689",
    "id": 128105754,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyODEwNTc1NA==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-08-05T18:49:25Z",
    "updated_at": "2015-08-05T18:49:25Z",
    "author_association": "MEMBER",
    "body": "Is this on your own server, or a public notebook server? It sounds like it's not happy about the HTTPS certificate.\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/175054974",
    "html_url": "https://github.com/ipython/ipython/issues/8689#issuecomment-175054974",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/8689",
    "id": 175054974,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE3NTA1NDk3NA==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-01-26T14:47:52Z",
    "updated_at": "2016-01-26T14:47:52Z",
    "author_association": "MEMBER",
    "body": "Closing as it's not clear what the issue was. If there is still something for us to fix, please open a new issue on the jupyter/notebook repo.\n"
  }
]
