[
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/229993518",
    "html_url": "https://github.com/ipython/ipython/issues/9686#issuecomment-229993518",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/9686",
    "id": 229993518,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyOTk5MzUxOA==",
    "user": {
      "login": "Carreau",
      "id": 335567,
      "node_id": "MDQ6VXNlcjMzNTU2Nw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/335567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Carreau",
      "html_url": "https://github.com/Carreau",
      "followers_url": "https://api.github.com/users/Carreau/followers",
      "following_url": "https://api.github.com/users/Carreau/following{/other_user}",
      "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions",
      "organizations_url": "https://api.github.com/users/Carreau/orgs",
      "repos_url": "https://api.github.com/users/Carreau/repos",
      "events_url": "https://api.github.com/users/Carreau/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Carreau/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-01T16:43:11Z",
    "updated_at": "2016-07-01T16:43:11Z",
    "author_association": "MEMBER",
    "body": "Hi there, \n\nYes, we are aware of that, there is not much we can do: from `IPython --help-all`:\n\n```\n--HistoryManager.hist_file=<Unicode>\n    Default: ''\n    Path to file to use for SQLite history database.\n    By default, IPython will put the history database in the IPython profile\n    directory.  If you would rather share one history among profiles, you can\n    set this value in each, so that they are consistent.\n    Due to an issue with fcntl, SQLite is known to misbehave on some NFS mounts.\n    If you see IPython hanging, try setting this to something on a local disk,\n    e.g::\n        ipython --HistoryManager.hist_file=/tmp/ipython_hist.sqlite\n```\n\nYou can also use the specific `:memory:` value to keep the history in ram. (#9687 should add that to the documentation)\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/229994424",
    "html_url": "https://github.com/ipython/ipython/issues/9686#issuecomment-229994424",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/9686",
    "id": 229994424,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyOTk5NDQyNA==",
    "user": {
      "login": "Carreau",
      "id": 335567,
      "node_id": "MDQ6VXNlcjMzNTU2Nw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/335567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Carreau",
      "html_url": "https://github.com/Carreau",
      "followers_url": "https://api.github.com/users/Carreau/followers",
      "following_url": "https://api.github.com/users/Carreau/following{/other_user}",
      "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions",
      "organizations_url": "https://api.github.com/users/Carreau/orgs",
      "repos_url": "https://api.github.com/users/Carreau/repos",
      "events_url": "https://api.github.com/users/Carreau/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Carreau/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-01T16:47:36Z",
    "updated_at": "2016-07-01T16:47:36Z",
    "author_association": "MEMBER",
    "body": "Hum, strangely we have a `_corrupt_db_counter` that should do that on its own...\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/229995639",
    "html_url": "https://github.com/ipython/ipython/issues/9686#issuecomment-229995639",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/9686",
    "id": 229995639,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyOTk5NTYzOQ==",
    "user": {
      "login": "Carreau",
      "id": 335567,
      "node_id": "MDQ6VXNlcjMzNTU2Nw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/335567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Carreau",
      "html_url": "https://github.com/Carreau",
      "followers_url": "https://api.github.com/users/Carreau/followers",
      "following_url": "https://api.github.com/users/Carreau/following{/other_user}",
      "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions",
      "organizations_url": "https://api.github.com/users/Carreau/orgs",
      "repos_url": "https://api.github.com/users/Carreau/repos",
      "events_url": "https://api.github.com/users/Carreau/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Carreau/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-01T16:52:56Z",
    "updated_at": "2016-07-01T16:52:56Z",
    "author_association": "MEMBER",
    "body": "> Hum, strangely we have a _corrupt_db_counter that should do that on its own...\n\nOh, actually that's only in master (#9418) , likely a duplicate of #9412, can you try with the current beta version ?\n\n```\n$ pip install ipython --pre --upgrade \n```\n"
  },
  {
    "url": "https://api.github.com/repos/ipython/ipython/issues/comments/278136181",
    "html_url": "https://github.com/ipython/ipython/issues/9686#issuecomment-278136181",
    "issue_url": "https://api.github.com/repos/ipython/ipython/issues/9686",
    "id": 278136181,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI3ODEzNjE4MQ==",
    "user": {
      "login": "Carreau",
      "id": 335567,
      "node_id": "MDQ6VXNlcjMzNTU2Nw==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/335567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Carreau",
      "html_url": "https://github.com/Carreau",
      "followers_url": "https://api.github.com/users/Carreau/followers",
      "following_url": "https://api.github.com/users/Carreau/following{/other_user}",
      "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions",
      "organizations_url": "https://api.github.com/users/Carreau/orgs",
      "repos_url": "https://api.github.com/users/Carreau/repos",
      "events_url": "https://api.github.com/users/Carreau/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Carreau/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-02-07T20:52:22Z",
    "updated_at": "2017-02-07T20:52:22Z",
    "author_association": "MEMBER",
    "body": "Closing as this has likely be fixed by #9418"
  }
]
